### ISSUE TITLE
Menu bar doesn't appear on Home or Members page on mobile

### ISSUE THREAD

**Issue by noahfranz13** [astro-sonata/astro-sonata.github.io#12]
On the mobile version of the website, the hamburger menu doesn't appear but the button still exists in the top right corner. I have no idea why this is going on and I spent a while trying to debug it this morning. @vikrammanikantan could you try taking a look?

**Comment by vikrammanikantan** [comment]
From my phone, looks like the button appears for all pages except Home and Members

**Comment by vikrammanikantan** [comment]
Fixed with commit #1622b7c. I don't understand why the fix works, but it works.
